# Generated by Django 2.2.9 on 2023-02-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230220_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='decription',
            new_name='description',
        ),
    ]
