# Generated by Django 2.2.9 on 2023-02-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230222_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.RemoveField(
            model_name='group',
            name='pub_date',
        ),
    ]
